### ISSUE TITLE
Bug Report: Glutton transforms into Ravenous while scoped in causes them to remain permanently scoped in

### ISSUE THREAD

**Issue by CptHaxray** [ZacharyHinds/ttt2-role-glutton#17]
**Description:**
If the Glutton transforms into the Ravenous while scoped in with a sniper rifle, they will have the scope overlay permanently even after they lose all of their weapons.

**Notes:**

- The Ravenous can still use their knife, they are simply stuck with the scope overlay and zoomed in view.

**Comment by ZacharyHinds** [comment]
I think this is actually an issue with [StripWeapons()](https://wiki.facepunch.com/gmod/Player:StripWeapons) but I'll see if I can work around that

**Comment by ZacharyHinds** [comment]
Fixed in most recent commit. Update pushed to Steam
