### ISSUE TITLE
Glutton Does not heal from eating bodies after reaching max allowed health

### ISSUE THREAD

**Issue by CptHaxray** [ZacharyHinds/ttt2-role-glutton#18]
Description:
When the Glutton eats a body, they will not recover any health if they've already reached the current maximum of health they are allowed to obtain.(For example, if the max health a glutton can get is 250, and they've raised their health to 250 by eating bodies, eating additional bodies will not heal them).

Notes:
-Its a bit unclear to me if this is an intentional feature or a bug. I was not aware of this until after the recent TTT2 update, as it seems the server I usually played on had modified the Glutton to let them heal health when eating bodies even when at max health.  Regardless if it is a bug or a feature, it is a massive quality of life to be able to continue to heal from eating bodies.

**Comment by ZacharyHinds** [comment]
Good catch, never noticed this issue before. [Fixed with latest commit ](https://github.com/ZacharyHinds/ttt2-role-glutton/commit/27116b23980c4dcb4294375c5f56409f3bbd911f)
